
frases = (' Os pequenos instantes que passo ao seu lado são os mais grandes e belos momentos em minha vida!',
          'Não sei se o mundo é bom, mas ele ficou muito melhor quando você chegou.',
          'Hoje eu preciso ouvir qualquer palavra tua, qualquer frase exagerada que me faça sentir alegria em estar vivo.',
          'O pacto que todo casal deveria fazer: ‘Quando eu achar que o amor está acabando, prometo me lembrar dos motivos que me fizeram te amar um dia’.',
          'Me faz um favor? Cuida bem do meu coração, pois ele pertence a você.',
          'Eu nunca me cansarei de dizer que é você quem eu amo, é você quem eu quero e é o seu lado que eu quero acordar todos os dias',
          'Posso passar muitos dias sem te ver, muitos dias sem te abraçar, mas isso nunca me fará parar de te amar',
          'E cada vez mais eu tenho certeza que a pessoa certa é você', 'O sorriso é meu, mas o motivo é você',
          'De tudo o que mais preciso, você é o que mais necessito ter!',
          'Meu amor, quero lhe agradecer por suportar meus defeitos, tolerar meus humores e, principalmente, por me entender. Amo você!',
          'Mesmo depois de conhecer vários novos sorrisos, o seu continua sendo o meu preferido.',
          'Amor é quando você se apaixona pela mesma pessoa todos os dias como se fosse a primeira vez.',
          'Quando Deus fez o mundo, espalhou por ele pessoas maravilhosas, e nos deu a missão de encontrá-las. Cumpri a minha, te encontrei.',
          'Não quero apenas te ver bem, eu quero ser a pessoa que vai te deixar bem.',
          'Com você, o meu mundo é melhor.', 'Todos vivem por uma razão, a minha é você.',
          'Percebi que era amor a partir do momento que eu não conseguia mais descrever, a partir do momento em que a única coisa que eu conseguia fazer era sentir.',
          'Se o amor é fantasia, eu me encontro ultimamente em pleno carnaval.',
          'Lindo é quando você olha para pessoa que ama e ela sorri para você.',
          'Tentei lhe dizer muitas coisas, mas acabei descobrindo que amar é muito mais sentir do que dizer. E milhões de frases bonitas, jamais alcançariam o que eu sinto por você.',
          'Uma boa relação é quando alguém aceita seu passado, apoia seu presente e motiva seu futuro.',
          'Tem amor que parece que nasceu pra durar uma vida inteira, tipo o meu por você.',
          'O mundo tem 3 oceanos, 7 mares, 5 continentes, 510 milhões de km² de terra e ainda assim, consegui achar alguém tão especial como você!',
          'Tem tanta coisa que eu quero viver com você…',
          'Eu tô apaixonado, eu tô contando tudo e não tô nem ligando pro que vão dizer. Amar não é pecado e se eu tiver errado que se dane o mundo eu só quero você.',
          'E agora eu sei, o quanto conhecer você foi bom para mim. Te amo!',
          'Nos teus lábios conheci as mais lindas palavras, que sempre desejava ouvir. Do teu coração conheci as maiores chamas, com as quais sempre sonhava aquecer-me. Que o nosso namoro seja eterno. Te amo!',
          'Avião sem asa, fogueira sem brasa, sou eu assim sem você. Futebol sem bola, Piu-piu sem Frajola, sou eu assim sem você.',
          'O melhor sentimento do mundo é ver alguém sorrir e saber que você é o motivo.',
          'Um dos motivos pelo qual eu te amo, é a segurança que você me traz. Pode ter certeza que ao teu lado, caminho até de olhos fechados.',
          'Amor igual ao teu eu nunca mais terei. Amor que eu nunca vi igual, que eu nunca mais verei. Amor que não se pede, amor que não se mede, que não se repete.',
          ' O tempo passa e o meu amor por você só aumenta a cada dia.',
          'Se o amor é pecado, jamais serei inocente, pois jurei a mim mesmo, amar-te eternamente!',
          'Ao seu lado descobri que entre o sonho e a realidade, existe um espaço chamado felicidade, e para que a minha felicidade se torne realidade, preciso estar ao seu lado.',
          'Te amo. Com todas as letras, palavras e pronúncias. Em todas as línguas e sotaques. Em todos os sentidos e jeitos. Com todas as circunstâncias e motivos. Simplesmente, te amo.',
          'Nosso amor é aquele sentimento forte, único e verdadeiro, que mesmo com o passar do tempo e com a distância que existe entre nós, jamais se desgastará, pois pertencemos um ao outro, juntos em um só coração. Te amo.',
          'Quando eu digo que te amo, não digo por força do hábito. Eu falo isso para te lembrar que você é a melhor coisa que aconteceu em minha vida.',
          'Sabe quando você quer que um momento dure para sempre? Então, é assim quando estou com você.',
          'Eu te amo. E nunca me imaginaria amando alguém com tanta intensidade, nem sabia que tinha tanta capacidade pra amar assim. Mas isso tudo por sua culpa. Ninguém além de você, saberia despertar isso em mim',
          'O casal perfeito não é aquele que nunca tem problemas, mas sim aquele que apesar dos obstáculos sempre permanece juntos',
          'Você é o maior presente que Deus poderia me dar. Te amo hoje e sempre!',
          'Que não falte bons sentimentos. Que nos falte egoísmo. Que nos sobre paciência. Que não nos falte esperança. Que cada caminho escolhido nos reserve boas surpresas. Que cada um de nós saiba ouvir cada conselho dado por uma pessoa mais velha. Que não nos falte vontade de sorrir. Que nenhum de nós se esqueça da força que possui. Que não falte fé e amor.',
          'Não existe um dia se quer em que eu não acorde pensando em você. E quer saber? Não há pensamento melhor, se não pensar em você.',
          'Minha felicidade não tem preço, tem o seu nome.',
          'Não importa se serão momentos bons ou ruins, mas se forem ao seu lado, cada segundo valerá a pena.',
          'Eu amo estar com você, eu amo ficar com você, seu cheirinho me faz viajar, sua voz me faz suspirar.',
          'Posso estar no pior dia da minha vida, mesmo assim vou fazer de tudo para ver você sorrir.',
          'Aprendi que o amor é feito de liberdade. É como ter todos os dias outras opções, e ainda assim fazer a mesma escolha.',
          'Um dia me disseram que o sorriso é uma forma de mostrarmos o quanto gostamos de alguém. Hoje me perguntaram se eu gostava de você eu apenas… sorri.',
          'Um dia me perguntaram “O que você viu nela?” e eu respondi “O que faltava em mim!',
'Trate sua namorada como uma rainha, respeite como uma dama, cuide como uma criança e ame-a como uma mulher.',
'O homem de verdade não é aquele que conquista várias mulheres, mas sim aquele tem o amor bastante, para conquistar a mesma, todos os dias',
'Por você, eu dançaria tango no teto, eu limparia os trilhos do metrô, eu iria a pé do Rio a Salvador.',
'Que tudo na sua vida brilhe como seus olhos, seja maravilhoso como seu coração, e linda como você.',
'Deus plantou e escolheu a mais bela flor de seu jardim e me deu, e essa flor é você.',
'Não quero a garota mais linda do mundo, quero a garota que faça do meu mundo o mais bonito.',
'Para conquistar uma mulher, coloque-se no lugar dela!',
'Ao seu lado não importa o que aconteça conseguirei achar motivos para me sentir feliz.',
'Não escolha a pessoa mais bonita do mundo. Escolha a pessoa que faz do seu mundo, o mais bonito.',
'Falar com você por 5 minutos me faz sorrir por 24 horas.',
'Eu poderia amar qualquer outra pessoa, uma pessoa menos complicada, menos indecisa, e que estivesse disposta a estar comigo toda hora. Mas meu coração te escolheu, e por alguma razão, ele não abre mão de você.',
'Quando eu estou em seus braços tudo parece tão certo. Eu sei que é onde eu deveria estar.',
'Não sei como te dizer, nem sei como te explicar, só sei que te amo e vivo pra te amar!',
'Dormir é bom, mas poderia ser melhor se fosse agarradinho com você.',
'Vivo tentando encontrar palavras pra te descrever, mas nada chega tão perto, e o que mais se aproxima é: perfeição.',
'Eu gosto de você. Aliás, eu gosto de tudo que me tira um sorriso espontâneo sem precisar de esforço para isso.',
'Se o seu amor sente ciúmes, agradeça a ele, pois isso é sinal que ele gosta de você!',
'De todas as coisas que eu preciso, você é a mais importante.',
'Daí você recebe um sms e passa o dia inteiro sorrindo.',
'Que as declarações sejam diárias e o amor seja constante!',
'Se existe felicidade perfeita eu não sei, mas perto de você me sinto perfeitamente feliz.',
'Não tenho todas as respostas, mas uma coisa que eu sei é que para onde você estiver indo é para onde eu quero ir.',
'Faria e faço de tudo pra te ver feliz.',
'Que vontade de te dar um beijo. Tomara que você já tenha aprendido a ler pensamentos.',
'Te ter é mais que um sonho bom, é desejar encontrar o que todos mais procuram nesse mundo, a felicidade.',
'Por trás de grandes namorados existem dois grandes amigos.',
'Por sua causa eu tenho lindos sonhos para sonhar. Por sua causa, minha vida está cheia de amor.',
'Quando a gente gosta é claro que a gente cuida.',
'Há pessoas que nos falam e nem as escutamos, há pessoas que nos ferem e nem cicatrizes deixam, mas há pessoas que simplesmente aparecem em nossas vidas e nos marcam para sempre.',
'E não existe um só dia que eu não pense em você.',
'Ele é meu anjo. Só que sem asas.',
'Eu estou sorrindo agora, e você é o motivo, não só do meu sorriso, mas também da minha felicidade.',
'Tem gente que me irrita fácil, tem gente que me faz bem fácil, e tem você, que faz os dois.',
'Às vezes tudo o que a gente precisa é um chá, um cafuné e um abraço apertado.',
'Eu gosto do labirinto dos seus braços. No pior dos casos: eu me perco em você.',
'O amor se torna favorável pelo carinho, não pela autoridade.',
'O espaço é infinito, mas não é maior que nosso sentimento, pois nós dois juntos somos o amor.',
'Quando alguém disser que te ama, duvide. Quando alguém provar que te ama, valorize.',
'Não me lembro mais qual foi nosso começo. Sei que não começamos pelo começo. Já era amor antes de ser.',
'A maior felicidade é a certeza de sermos amados apesar de ser como somos.',
'Fale comigo sempre que você estiver triste, mesmo que eu não consiga lhe trazer a felicidade, eu lhe darei muito amor',
'Então, naquele dia que você me olhou. Me balançou por dentro, me virou o mundo! Percebi, tinha que ser você',
'Você não tem a menor noção do seu efeito sobre mim.',
'E tem uma parte de mim que não sou eu. É um resto de você.',
'No homem há mais amor-próprio do que amor; na mulher, pelo contrário, há mais amor do que amor-próprio.',
'Me conquistar é complicado, me ter é destino, me amar é inevitável, me perder é um risco, me esquecer… Tenta que eu quero ver.',
'Cada qual sabe amar a seu modo; o modo, pouco importa; o essencial é que saiba amar.',
'Nunca deixe de ter um sorriso em seu rosto, pois eu preciso dele.',
'O amor se renova e fortalece no namoro do dia-a-dia.')



print('='*40)
print((' FRASES DE AMOR PARA MEU AMOR '.center(40)))
print('='*40)

while True:
    x = int(input(('Escolhe um número de 1 à 100 para ver uma frase bonitinha -> ')))
    if x < 0 or x > 100:
        print('Esse ainda não tem amor, Tenta outro entre 1 e 100')
        continue
    else:
        break

print((f'\n{frases[x+1]}'))
seg = str(input(('\nSó poder ver um por dia em amor!!!, Agora aperta Enter para fechar ou sai no X, I Love You')))

